### ISSUE TITLE
Not working with latest libnx and 12.1.0

### ISSUE THREAD

**Issue by pathartl** [Cpasjuste/eduke32#1]
I compiled from 148e06b5419e4002a0d68b3d2a7857758bd4fde1 and the build does not work on 12.1.0. It compiles fine, but crashes upon start.

**Comment by Cpasjuste** [comment]
Hi, thanks for the report. I'm going to take a look right now but not sure if i'll have the time to fix this today !

**Comment by Cpasjuste** [comment]
Hi, could you try this build: https://github.com/Cpasjuste/eduke32/releases/tag/v1.5

It works fine here on 12.0.3 AMS, was built with "make PLATFORM=SWITCH RELEASE=1"

**Comment by pathartl** [comment]
Works on 12.1.0 AMS! Behold, the smallest pull request ever made
